### ISSUE TITLE
Unable to compile using qt5

### ISSUE THREAD

**Issue by supportreq** [owncloud/homebrew-owncloud#1]
Hi,

I am trying to compile the MAC client with QT5. 

$brew install qt5
The same executed successfully but getting an error for qtkeychain

$brew install qtkeychain

==> Downloading https://github.com/frankosterfeld/qtkeychain/archive/0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/qtkeychain-0.3.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qtkeychain/0.3 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
  CMakeLists.txt:19 (find_package)

Please advice

**Comment by ghost** [comment]
Hi there.

Can you help with my compile error:  **fatal error: 'keychain.h' file not found**?

SHORT BACKGROUND
Because there is no Mac Desktop client that supports the End-to-End Encryption (E2EE), I'm trying to compile the Desktop client myself onto my Mac High Sierra 10.13.4 (latest version as of this writing).

I've had to install a number of extra packages:

brew install openssl wget cmake

wget https://github.com/sparkle-project/Sparkle/releases/download/1.19.1a1/Sparkle-1.19.1a1.tar.bz2
tar -xf Sparkle-1.19.1a1.tar.bz2
mv -v Sparkle.framework ~/Library/Frameworks/

===== missing brew packages =====
brew install sphinx syncthing-inotify

CMAKE:
cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=/Users/<username>/client/install/  -DNO_SHIBBOLETH=1 -DQTKEYCHAIN_INCLUDE_DIR=/usr/local/Cellar/qtkeychain/0.8.0 -DQTKEYCHAIN_LIBRARY=/usr/local/Cellar/qtkeychain/0.8.0/lib/libqt5keychain.dylib

MAKE ERROR:
CMakeFiles/nextcloudsync.dir/clientsideencryption.cpp.o -c /Users/<username>/client/src/libsync/clientsideencryption.cpp
/Users/<username>/client/src/libsync/clientsideencryption.cpp:32:10: fatal error: 'keychain.h' file not
      found
#include <keychain.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [src/libsync/CMakeFiles/nextcloudsync.dir/clientsideencryption.cpp.o] Error 1
make[1]: *** [src/libsync/CMakeFiles/nextcloudsync.dir/all] Error 2
make: *** [all] Error 2
